-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfFCdegkSuSG/xdck
oPv09v3RHhhGUIQlXEwp9w2hudCgCgYIKoZIzj0DAQehRANCAARwZ10MHRwqL9Ai
zFI2qbRMYctZOKEr3LGgQte1fuZMWYtZHY8OejM9b41oGhkQcHcPFqVzwfkijhXx
blcHH6R7
-----END PRIVATE KEY-----