name: meshi
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: ^0.21.0
  http: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - res/images/
    - res/icons/


  fonts:
    - family: BettyLavea
      fonts:
      - asset: res/fonts/BettyLavea.ttf

    - family: Poppins
      fonts:
      - asset: res/fonts/Poppins-Regular.ttf
      - asset: res/fonts/Poppins-Italic.ttf
        style: italic
      - asset: res/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: res/fonts/Poppins-Light.ttf
        weight: 300
      - asset: res/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: res/fonts/Poppins-Black.ttf
        weight: 900

    # For details regarding fonts from package dependencies,
    # see https://flutter.io/custom-fonts/#from-packages