name: meshi
description: Meshi mobile app.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev.0.5.flutter-a1668566e5 <3.0.0"

dependencies:
  url_launcher: ^5.0.3
  webview_flutter: ^0.3.9+1
  adhara_socket_io: ^0.1.10
  dio: 2.1.3
  json_annotation: ^2.2.0
  shared_preferences: ^0.5.2
  flutter_facebook_login: ^2.0.0
  dependencies_flutter: ^0.1.6
  sqflite: ^1.1.0
  rxdart: ^0.22.0
  http: ^0.12.0+2
  image_picker: ^0.6.0+9
  flutter_range_slider: ^1.1.0
  flutter_launcher_icons: ^0.7.0
  flutter_counter: ^1.0.3
  cupertino_icons: ^0.1.2
  json_serializable: ^2.2.1
  cached_network_image: ^0.8.0
  bloc: ^0.13.0
  flutter_bloc: ^0.13.0
  equatable: ^0.2.3
  carousel_slider: ^1.3.0
  flutter:
    sdk: flutter


dev_dependencies:
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


flutter_icons:
  ios: true
  android: true
  image_path: "res/icons/launcher/app_launcher.png"
#  image_path_android: "res/icons/launcher/app_launcher.png"
  adaptive_icon_background: "res/icons/launcher/background.png"
  adaptive_icon_foreground: "res/icons/launcher/foreground.png"



flutter:

  uses-material-design: true

  assets:
  - res/icons/

  fonts:
  - family: BettyLavea
    fonts:
    - asset: res/fonts/BettyLavea.ttf

  - family: Poppins
    fonts:
    - asset: res/fonts/Poppins-Regular.ttf
    - asset: res/fonts/Poppins-Italic.ttf
      style: italic
    - asset: res/fonts/Poppins-Thin.ttf
      weight: 100
    - asset: res/fonts/Poppins-Light.ttf
      weight: 300
    - asset: res/fonts/Poppins-Bold.ttf
      weight: 700
    - asset: res/fonts/Poppins-Black.ttf
      weight: 900

