name: meshi
description: A new Flutter application.

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_facebook_login: ^2.0.0
  rxdart: ^0.21.0
  http: ^0.12.0+2
  image_picker: ^0.5.0+6
  flutter_range_slider: ^1.1.0
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  ios: true
  android: true
  image_path: "res/icons/launcher/app_launcher.png"
#  image_path_android: "res/icons/launcher/app_launcher.png"
  adaptive_icon_background: "res/icons/launcher/background.png"
  adaptive_icon_foreground: "res/icons/launcher/foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
  - res/images/
  - res/icons/

  fonts:
  - family: BettyLavea
    fonts:
    - asset: res/fonts/BettyLavea.ttf

  - family: Poppins
    fonts:
    - asset: res/fonts/Poppins-Regular.ttf
    - asset: res/fonts/Poppins-Italic.ttf
      style: italic
    - asset: res/fonts/Poppins-Thin.ttf
      weight: 100
    - asset: res/fonts/Poppins-Light.ttf
      weight: 300
    - asset: res/fonts/Poppins-Bold.ttf
      weight: 700
    - asset: res/fonts/Poppins-Black.ttf
      weight: 900

